export const avatars = {
  'avatar1': '/images/avatars/avatar1.svg',
  'avatar2': '/images/avatars/avatar2.svg',
  'avatar3': '/images/avatars/avatar3.svg',
  'avatar4': '/images/avatars/avatar4.svg',
  'avatar5': '/images/avatars/avatar5.svg',
  'avatar6': '/images/avatars/avatar6.svg',
  'avatar7': '/images/avatars/avatar7.svg',
  'avatar8': '/images/avatars/avatar8.svg',
  'avatar9': '/images/avatars/avatar9.svg',
  'avatar10': '/images/avatars/avatar10.svg',
  'avatar11': '/images/avatars/avatar11.svg',
  'avatar12': '/images/avatars/avatar12.svg',
  'avatar13': '/images/avatars/avatar13.svg',
  'avatar14': '/images/avatars/avatar14.svg',
  'avatar15': '/images/avatars/avatar15.svg',
  'avatar16': '/images/avatars/avatar16.svg',
  'avatar17': '/images/avatars/avatar17.svg',
  'avatar18': '/images/avatars/avatar18.svg',
  'avatar19': '/images/avatars/avatar19.svg',
  'avatar20': '/images/avatars/avatar20.svg'
}